---
title: "Prepare Phenotypic Data"
author: "LucianoRogerio"
date: "2022-04-26"
output: workflowr::wflow_html
editor_options:
  chunk_output_type: console
---

In this Section we will obtain the deregressed BLUPs and BLUPs for each clone evaluated to tolerance to Foliar Disease in Cassava.

## Packages required

```{r read the packages}
library(here)
library(tidyverse)
library(sommer)
library(reshape2)
library(data.table)
```

## Read and prepare the Phenotypic data for the Mixed Models Analysis

```{r Read the Phenotypic data}
PhenoData <- read.table(file = here::here("data", "DadosDoencasBAG2021-22Henr.csv"),
                        header = T, sep = ",") %>%
  mutate(block_number = as.character(block_number),
         Year = ifelse(trial_name == "BR.PTBAG.20.Candeal", yes = "20", no = "21")) %>% 
  mutate(YearRep = paste(Year, block_number, sep = ".")) %>% 
  dplyr::select(1:13, Year, YearRep, everything())

PhenoData2 <- PhenoData %>% reshape2::melt(data = ., id.vars = c(1:15),
                                           variable.name = "Trait",
                                           value.name = "Value") %>% 
  filter(!is.na(Value)) %>% rename(GID = accession_name)
head(PhenoData)
```


## Mixed Models

```{r Mixed Models, eval = FALSE}
library(sommer); library(data.table)
library(tidyverse)

tiff(filename = here::here("output", "DataBar.tiff"), compression = "lzw",
     units = "cm", res = 200, width = 12, height = 10)
PhenoData2 %>% ggplot(aes(x = Value, fill = Trait)) + geom_bar() + facet_wrap(~Trait) + theme_bw()
dev.off()



NCT <- 5
RhpcBLASctl ::blas_set_num_threads(NCT)
MM <- mmer(fixed = Anthractnose ~ block_number,
           random = ~ accession_name,
           data = PhenoData %>% filter(Year == "21"))

MM2 <- mmer(fixed = ManchaBranca ~ block_number,
           random = ~ accession_name,
           data = PhenoData %>% filter(Year == "21"))

MM3 <- mmer(fixed = ManchaParda ~ block_number,
           random = ~ accession_name,
           data = PhenoData %>% filter(Year == "21"))

MM4 <- mmer(fixed = QueimaFolhas ~ block_number,
           random = ~ accession_name,
           data = PhenoData %>% filter(Year == "21"))


Blups <- tibble(Clones = MM$U$accession_name$Anthractnose %>% names,
  Anth = MM$U$accession_name$Anthractnose)

Blups2  <- tibble(Clones = MM2$U$accession_name$ManchaBranca %>% names,
  MB = MM2$U$accession_name$ManchaBranca)

Blups3  <- tibble(Clones = MM3$U$accession_name$ManchaParda %>% names,
  MP = MM3$U$accession_name$ManchaParda)

Blups4  <- tibble(Clones = MM4$U$accession_name$QueimaFolhas %>% names,
  QF = MM4$U$accession_name$QueimaFolhas)

BlupsF <- Blups %>% full_join(Blups2, by = "Clones") %>% 
  full_join(Blups3, by = "Clones") %>% 
  full_join(Blups4, by = "Clones") %>% 
  mutate(Clones = gsub(x = Clones, pattern = "accession_name",
                       replacement = ""))

write.table(BlupsF, file = here::here("output", "Blups.csv"), sep = ",",
            quote = F, row.names = F)

BlupsF2 <- BlupsF %>% reshape2::melt(value.name = "y", id.vars = "Clones",
                                     variable.name = "Trait")

tiff(filename = here::here("output", "BlupsDensity.tiff"), compression = "lzw",
     units = "cm", res = 200, width = 12, height = 10)
BlupsF2 %>% ggplot(aes(x = y, fill = Trait)) + geom_density() + facet_wrap(~Trait) + theme_bw()
dev.off()

Manchas22 <- tibble(Trait = "Ant",
                    VarG = MM$sigma$accession_name,
                    VarE = MM$sigma$units,
                    H2 = VarG/(VarE + VarG)) %>% 
  bind_rows(tibble(Trait = "MB",
                    VarG = MM2$sigma$accession_name,
                    VarE = MM2$sigma$units,
                    H2 = VarG/(VarE + VarG))) %>% 
  bind_rows(tibble(Trait = "MP",
                    VarG = MM3$sigma$accession_name,
                    VarE = MM3$sigma$units,
                    H2 = VarG/(VarE + VarG))) %>% 
              bind_rows(tibble(Trait = "QF",
                    VarG = MM4$sigma$accession_name,
                    VarE = MM4$sigma$units,
                    H2 = VarG/(VarE + VarG)))

write.table(Manchas22, file = here::here("output", "herdabilidadesHen.csv"), sep = ",",
            quote = F, row.names = F)

BlupsF


MM <- mmer(fixed = cbind(Anthractnose, ManchaBranca, ManchaParda, QueimaFolhas) ~ 1,
           random = ~ accession_name + YearRep, getPEV = T, data = PhenoData)
MM$AIC
#1394.834
#946.3573?

load("output/MMResults.RData")
anova(MM)
MM <-  mmer(fixed = cbind(Anthractnose, ManchaBranca, ManchaParda, QueimaFolhas) ~ block_number,
            random = ~ accession_name, getPEV = T, data = PhenoData)

Nmean <- PhenoData %>% count(accession_name) %>% summarize(mean(n))

CompVar <- tibble(Trait = unique(MM$Beta$Trait) %>% as.character,
                  Vg = MM$sigma$`accession_name:new` %>% diag %>% as.vector,
                  Ve = MM$sigma$units %>% diag %>% as.vector,
                  H2 = Vg/(Vg + (Ve/Nmean[[1]])))

Blups <- tibble(Trait = unique(MM$Beta$Trait) %>% as.character) %>%
  mutate(Estimate = list(tibble(clones = names(MM$U$`accession_name:new`[[Trait[[1]]]]) %>%
                                  gsub(pattern = "accession_name", replacement = "") %>%
                                  gsub(pattern = ":new", replacement = ""),
                                BLUP = MM$U$`accession_name`[[Trait[[1]]]],
                                PEV = diag(MM$PevU$`accession_name`[[Trait[[1]]]],),
                                REL = 1 - PEV/CompVar[CompVar$Trait == Trait[[1]], "Vg"][[1]],
                                drgBLUP = BLUP/REL,
                                WT = (1 - CompVar[CompVar$Trait == Trait[[1]], "H2"][[1]])/((0.1 + (1 - REL)/REL)*CompVar[CompVar$Trait == Trait[[1]], "H2"][[1]]))))

saveRDS(Blups, file = here::here("output", ""))
```

